name: cadiz_tren_bus_tranvia_catamaran
description: "Proyecto con horarios del transporte público en la provincia de Cádiz"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  go_router: ^17.3.0
  drift: ^2.34.0
  sqlite3_flutter_libs: ^0.6.0
  path_provider: ^2.1.3
  path: ^1.9.0
  sqlite3: ^3.3.4
  flex_color_scheme: ^8.4.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.4
  build_runner: ^2.15.0
  drift_dev: ^2.34.0

dependency_overrides:
  meta: 1.18.0
  test_api: 0.7.13
  analyzer: 12.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/cadiz_transit.sqlite
