// This worker file is needed to use drift on the web.
// It's usually generated by drift_dev or can be a simple script that imports the drift web library.
// For a simple setup, we can use the one provided by drift.
importScripts('https://unpkg.com/drift/dist/drift_worker.js');
